// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'check': string;
  'description': string;
  'field': string;
  'label': string;
  'notices': string;
  'tipIcon': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
